//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOrg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.DesingWork = new HashSet<DesingWork>();
        }
    
        public int DealID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int OrganizationID { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesingWork> DesingWork { get; set; }

        public string OrgName
        {
            get
            {
                return Organization.Title;
            }
        }

        public string OrgType
        {
            get
            {
                return Organization.OrgTypeTitle;
            }
        }
    }
}
