//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOrg
{
    using System;
    using System.Collections.Generic;

    public partial class DesingWork
    {
        public int DesignWorkID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int dealID { get; set; }
        public int DepartmentID { get; set; }
        public string Image { get; set; }

        public virtual Deal Deal { get; set; }
        public virtual Department Department { get; set; }
        public string DepartmentName
        {
            get
            {
                return Department.DepartmentName;
            }
        }

        public string OrgName
        {
            get
            {
                return Deal.OrgName;
            }
        }
        public string OrgType
        {
            get
            {
                return Deal.OrgType;
            }
        }
    }
}
