//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOrg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectOranizationDBEntities2 : DbContext
    {
        public ProjectOranizationDBEntities2()
            : base("name=ProjectOranizationDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static ProjectOranizationDBEntities2 _context;
        public static ProjectOranizationDBEntities2 GetContext()
        {
            if (_context == null) _context = new ProjectOranizationDBEntities2();
            return _context;
        }

        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DesingWork> DesingWork { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<JobTitles> JobTitles { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<OrgType> OrgType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
